if has('win32') || has ('win64')
  let $VIMHOME = $HOME . "/vimfiles"
else
  let $VIMHOME = $HOME . "/.vim"
endif

""" Plugin section
set nocompatible
filetype off
let &rtp .= "," . $VIMHOME . "/bundle/Vundle.vim"

call vundle#begin()

Plugin 'mattn/emmet-vim'
Plugin 'ap/vim-css-color'
Plugin 'preservim/nerdcommenter'
Plugin 'dense-analysis/ale'

call vundle#end()

""" Plugin related section


""" Vanilla section
let mapleader=" "

filetype plugin on
filetype indent on
syntax on

set autoindent
set smartindent
set nobackup
set ffs=unix
set ff=unix
set hlsearch

let mapleader=" "
colorscheme peachpuff
set tabstop=4 shiftwidth=4 colorcolumn=81

function! CharAtCursor()
  return strcharpart(strpart(getline('.'), col('.') - 1), 0, 1)
endfunction

function! Execute(command)
  redir =>output
  silent exec a:command
  redir END
  return output
endfunction

"nnoremap <esc> :noh<return><esc> (breaks)
set backspace=indent,eol,start

inoremap <down> <esc>gja
inoremap <up> <esc>gka
nnoremap <down> gj
nnoremap <up> gk

nnoremap <leader>h :noh

nnoremap <leader><leader> /++<CR>:noh<CR>d2li
