if has('win32') || has ('win64')
  let $VIMHOME = $HOME . "/vimfiles"
else
  let $VIMHOME = $HOME . "/.vim"
endif

""" Plugin section
set nocompatible
filetype off
let &rtp .= "," . $VIMHOME . "/bundle/Vundle.vim"

call vundle#begin()

Plugin 'mattn/emmet-vim'
Plugin 'ap/vim-css-color'
Plugin 'dense-analysis/ale'

call vundle#end()

""" Plugin related section


""" Vanilla section
let mapleader=" "

filetype plugin on
filetype indent on
syntax on

set autoindent
set smartindent
set nobackup
set ffs=unix
set ff=unix
set hlsearch

let mapleader=" "
colorscheme peachpuff
set tabstop=4 shiftwidth=4 colorcolumn=81

function! CharAtCursor()
  return strcharpart(strpart(getline('.'), col('.') - 1), 0, 1)
endfunction

"nnoremap <esc> :noh<return><esc> (breaks)
set backspace=indent,eol,start

inoremap <expr> <down> ""
inoremap <expr> <up> ""
inoremap <expr> <left> ""
inoremap <expr> <right> ""
nnoremap <expr> <down> ""
nnoremap <expr> <up> ""
nnoremap <expr> <left> ""
nnoremap <expr> <right> ""

nnoremap <leader>h :noh

nnoremap <leader><leader> /++<CR>:noh<CR>c2l

" nnoremap <leader>a :!auto<space>%<CR> " breaks too
